SELECT a.TITLE
      ,a.BOARD_ID
      ,b.REPLY_ID
      ,b.WRITER_ID
      ,b.CONTENTS
      ,DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d')  CREATED_DATE
  FROM USED_GOODS_BOARD a
  JOIN USED_GOODS_REPLY b ON b.BOARD_ID = a.BOARD_ID
 WHERE DATE_FORMAT(a.CREATED_DATE, '%Y-%m') = '2022-10'
 ORDER BY b.CREATED_DATE ASC, a.TITLE ASC